import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import clsx from "clsx";
import "@/styles/globals.css";
import "@/styles/core.min.css";
import "@/styles/theme-default.min.css";
import 'boxicons/css/boxicons.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap", // Thêm thuộc tính display để tránh lỗi flash khi tải font
});



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div className="layout-wrapper">
          <div className="layout-container">
            <div className="layout-page">
              <div className="content-wrapper">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
